const countries = [
	{"iso": "AF", "iso3": "AFG", "nome": "Afeganistão", "nomeFormal": "República Islâmica do Afeganistão"},
	{"iso": "AL", "iso3": "ALB", "nome": "Albânia", "nomeFormal": "República da Albânia"},
	{"iso": "DZ", "iso3": "DZA", "nome": "Algéria", "nomeFormal": "República Democrática Popular da Algéria"},
	{"iso": "AS", "iso3": "ASM", "nome": "Samoa Americana", "nomeFormal": "Território de Samoa Americana"},
	{"iso": "AD", "iso3": "AND", "nome": "Andorra", "nomeFormal": "Principado Andorra"},
	{"iso": "AO", "iso3": "AGO", "nome": "Angola", "nomeFormal": "República de Angola"},
	{"iso": "AI", "iso3": "AIA", "nome": "Anguilla", "nomeFormal": "Anguilla"},
	{"iso": "AQ", "iso3": "ATA", "nome": "Antártida", "nomeFormal": "Antártida"},
	{"iso": "AG", "iso3": "ATG", "nome": "Antigua e Barbuda", "nomeFormal": "Antigua e Barbuda"},
	{"iso": "AR", "iso3": "ARG", "nome": "Argentina", "nomeFormal": "República Argentina"},
	{"iso": "AM", "iso3": "ARM", "nome": "Armênia", "nomeFormal": "República da Armênia"},
	{"iso": "AW", "iso3": "ABW", "nome": "Aruba", "nomeFormal": "Aruba"},
	{"iso": "AU", "iso3": "AUS", "nome": "Austrália", "nomeFormal": "Comunidade da Austrália"},
	{"iso": "AT", "iso3": "AUT", "nome": "Áustria", "nomeFormal": "República da Áustria"},
	{"iso": "AZ", "iso3": "AZE", "nome": "Azerbaijão", "nomeFormal": "República do Azerbaijão"},
	{"iso": "BS", "iso3": "BHS", "nome": "Bahamas", "nomeFormal": "Comunidade de Bahamas"},
	{"iso": "BH", "iso3": "BHR", "nome": "Bahrein", "nomeFormal": "Reino do Bahrein"},
	{"iso": "BD", "iso3": "BGD", "nome": "Bangladesh", "nomeFormal": "República Popular de Bangladesh"},
	{"iso": "BB", "iso3": "BRB", "nome": "Barbados", "nomeFormal": "Barbados"},
	{"iso": "BY", "iso3": "BLR", "nome": "Bielorrússia", "nomeFormal": "República da Bielorrússia"},
	{"iso": "BE", "iso3": "BEL", "nome": "Bélgica", "nomeFormal": "Reino da Bélgica"},
	{"iso": "BZ", "iso3": "BLZ", "nome": "Belize", "nomeFormal": "Belize"},
	{"iso": "BJ", "iso3": "BEN", "nome": "Benin", "nomeFormal": "República do Benin"},
	{"iso": "BM", "iso3": "BMU", "nome": "Bermuda", "nomeFormal": "Bermuda"},
	{"iso": "BT", "iso3": "BTN", "nome": "Butão", "nomeFormal": "Reino do Butão"},
	{"iso": "BO", "iso3": "BOL", "nome": "Bolívia", "nomeFormal": "Estado Plurinacional da Bolívia"},
	{"iso": "BA", "iso3": "BIH", "nome": "Bósnia e Herzegovina", "nomeFormal": "Bósnia e Herzegovina"},
	{"iso": "BW", "iso3": "BWA", "nome": "Botswana", "nomeFormal": "República da Botswana"},
	{"iso": "BV", "iso3": "BVT", "nome": "Ilha Bouvet", "nomeFormal": "Ilha Bouvet"},
	{"iso": "BR", "iso3": "BRA", "nome": "Brasil", "nomeFormal": "República Federativa do Brasil"},
	{"iso": "IO", "iso3": "IOT", "nome": "Território Britânico do Oceano Índico", "nomeFormal": "Território Britânico do Oceano Índico"},
	{"iso": "BN", "iso3": "BRN", "nome": "Brunei", "nomeFormal": "Estado do Brunei Darussalam"},
	{"iso": "BG", "iso3": "BGR", "nome": "Bulgária", "nomeFormal": "República da Bulgária"},
	{"iso": "BF", "iso3": "BFA", "nome": "Burkina Faso", "nomeFormal": "Burkina Faso"},
	{"iso": "BI", "iso3": "BDI", "nome": "Burundi", "nomeFormal": "República do Burundi"},
	{"iso": "KH", "iso3": "KHM", "nome": "Camboja", "nomeFormal": "Reino do Camboja"},
	{"iso": "CM", "iso3": "CMR", "nome": "Camarões", "nomeFormal": "República de Camarões"},
	{"iso": "CA", "iso3": "CAN", "nome": "Canadá", "nomeFormal": "Canadá"},
	{"iso": "CV", "iso3": "CPV", "nome": "Cabo Verde", "nomeFormal": "República do Cabo Verde"},
	{"iso": "KY", "iso3": "CYM", "nome": "Ilhas Cayman", "nomeFormal": "Ilhas Cayman"},
	{"iso": "CF", "iso3": "CAF", "nome": "República Centro-Africana", "nomeFormal": "República Centro-Africana"},
	{"iso": "TD", "iso3": "TCD", "nome": "Chade", "nomeFormal": "República do Chade"},
	{"iso": "CL", "iso3": "CHL", "nome": "Chile", "nomeFormal": "República do Chile"},
	{"iso": "CN", "iso3": "CHN", "nome": "China", "nomeFormal": "República Popular da China"},
	{"iso": "CX", "iso3": "CXR", "nome": "Ilha Christmas", "nomeFormal": "Território da Ilha Christmas"},
	{"iso": "CC", "iso3": "CCK", "nome": "Ilhas Cocos (Keeling)", "nomeFormal": "Território das Ilhas Cocos (Keeling)"},
	{"iso": "CO", "iso3": "COL", "nome": "Colômbia", "nomeFormal": "República da Colômbia"},
	{"iso": "KM", "iso3": "COM", "nome": "Comores", "nomeFormal": "União das Comores"},
	{"iso": "CG", "iso3": "COG", "nome": "Congo", "nomeFormal": "República do Congo"},
	{"iso": "CD", "iso3": "COD", "nome": "Congo (DR)", "nomeFormal": "República Democrática do Congo"},
	{"iso": "CK", "iso3": "COK", "nome": "Ilhas Cook", "nomeFormal": "Ilhas Cook"},
	{"iso": "CR", "iso3": "CRI", "nome": "Costa Rica", "nomeFormal": "República da Costa Rica"},
	{"iso": "CI", "iso3": "CIV", "nome": "Costa do Marfim", "nomeFormal": "República da Costa do Marfim"},
	{"iso": "HR", "iso3": "HRV", "nome": "Croácia", "nomeFormal": "República da Croácia"},
	{"iso": "CU", "iso3": "CUB", "nome": "Cuba", "nomeFormal": "República de Cuba"},
	{"iso": "CY", "iso3": "CYP", "nome": "Chipre", "nomeFormal": "República do Chipre"},
	{"iso": "CZ", "iso3": "CZE", "nome": "República Tcheca", "nomeFormal": "República Tcheca"},
	{"iso": "DK", "iso3": "DNK", "nome": "Dinamarca", "nomeFormal": "Reino da Dinamarca"},
	{"iso": "DJ", "iso3": "DJI", "nome": "Djibuti", "nomeFormal": "República do Djibuti"},
	{"iso": "DM", "iso3": "DMA", "nome": "Dominica", "nomeFormal": "Comunidade da Dominica"},
	{"iso": "DO", "iso3": "DOM", "nome": "República Dominicana", "nomeFormal": "República Dominicana"},
	{"iso": "EC", "iso3": "ECU", "nome": "Equador", "nomeFormal": "República do Equador"},
	{"iso": "EG", "iso3": "EGY", "nome": "Egito", "nomeFormal": "República Árabe do Egito"},
	{"iso": "SV", "iso3": "SLV", "nome": "El Salvador", "nomeFormal": "República El Salvador"},
	{"iso": "GQ", "iso3": "GNQ", "nome": "Guiné Equatorial", "nomeFormal": "República do Guiné Equatorial"},
	{"iso": "ER", "iso3": "ERI", "nome": "Eritreia", "nomeFormal": "Estado da Eritreia"},
	{"iso": "EE", "iso3": "EST", "nome": "Estônia", "nomeFormal": "República da Estônia"},
	{"iso": "ET", "iso3": "ETH", "nome": "Etiópia", "nomeFormal": "República Democrática Federal da Etiópia"},
	{"iso": "FK", "iso3": "FLK", "nome": "Ilhas Malvinas", "nomeFormal": "Ilhas Malvinas"},
	{"iso": "FO", "iso3": "FRO", "nome": "Ilhas Faroe", "nomeFormal": "Ilhas Faroe"},
	{"iso": "FJ", "iso3": "FJI", "nome": "Fiji", "nomeFormal": "República do Fiji"},
	{"iso": "FI", "iso3": "FIN", "nome": "Finlândia", "nomeFormal": "República da Finlândia"},
	{"iso": "FR", "iso3": "FRA", "nome": "França", "nomeFormal": "República Francesa"},
	{"iso": "GF", "iso3": "GUF", "nome": "Guiana Francesa", "nomeFormal": "Guiana Francesa"},
	{"iso": "PF", "iso3": "PYF", "nome": "Polinésia Francesa", "nomeFormal": "Polinésia Francesa"},
	{"iso": "TF", "iso3": "ATF", "nome": "Terras Austrais e Antárticas Francesas", "nomeFormal": "Território das Terras Austrais e Antárticas Francesas"},
	{"iso": "GA", "iso3": "GAB", "nome": "Gabão", "nomeFormal": "República Gabonesa"},
	{"iso": "GM", "iso3": "GMB", "nome": "Gâmbia", "nomeFormal": "República da Gâmbia"},
	{"iso": "GE", "iso3": "GEO", "nome": "Geórgia", "nomeFormal": "Geórgia"},
	{"iso": "DE", "iso3": "DEU", "nome": "Alemanha", "nomeFormal": "República Federal da Alemanha"},
	{"iso": "GH", "iso3": "GHA", "nome": "Gana", "nomeFormal": "Repúblia de Gana"},
	{"iso": "GI", "iso3": "GIB", "nome": "Gibraltar", "nomeFormal": "Gibraltar"},
	{"iso": "GR", "iso3": "GRC", "nome": "Grécia", "nomeFormal": "República Helênica"},
	{"iso": "GL", "iso3": "GRL", "nome": "Groelândia", "nomeFormal": "Groelândia"},
	{"iso": "GD", "iso3": "GRD", "nome": "Granada", "nomeFormal": "Granada"},
	{"iso": "GP", "iso3": "GLP", "nome": "Guadalupe", "nomeFormal": "Guadalupe"},
	{"iso": "GU", "iso3": "GUM", "nome": "Guão", "nomeFormal": "Território do Guão"},
	{"iso": "GT", "iso3": "GTM", "nome": "Guatemala", "nomeFormal": "República da Guatemala"},
	{"iso": "GN", "iso3": "GIN", "nome": "Guiné", "nomeFormal": "República do Guiné"},
	{"iso": "GW", "iso3": "GNB", "nome": "Guiné-Bissau", "nomeFormal": "República da Guiné-Bissau"},
	{"iso": "GY", "iso3": "GUY", "nome": "Guiana", "nomeFormal": "República Cooperativa da Guiana"},
	{"iso": "HT", "iso3": "HTI", "nome": "Haiti", "nomeFormal": "República do Haiti"},
	{"iso": "HM", "iso3": "HMD", "nome": "Ilhas Heard e McDonald", "nomeFormal": "Território das Ilhas Heard e McDonald"},
	{"iso": "VA", "iso3": "VAT", "nome": "Vaticano", "nomeFormal": "Estado da Cidade do Vaticano"},
	{"iso": "HN", "iso3": "HND", "nome": "Honduras", "nomeFormal": "República de Honduras"},
	{"iso": "HK", "iso3": "HKG", "nome": "Hong Kong", "nomeFormal": "Região Administrativa Especial de Hong Kong da República Popular da China"},
	{"iso": "HU", "iso3": "HUN", "nome": "Hungria", "nomeFormal": "Hungria"},
	{"iso": "IS", "iso3": "ISL", "nome": "Islândia", "nomeFormal": "Islândia"},
	{"iso": "IN", "iso3": "IND", "nome": "Índia", "nomeFormal": "República da Índia"},
	{"iso": "ID", "iso3": "IDN", "nome": "Indonésia", "nomeFormal": "República da Indonésia"},
	{"iso": "IR", "iso3": "IRN", "nome": "Iran", "nomeFormal": "República Islâmica do Iran"},
	{"iso": "IQ", "iso3": "IRQ", "nome": "Iraque", "nomeFormal": "República do Iraque"},
	{"iso": "IE", "iso3": "IRL", "nome": "Irlanda", "nomeFormal": "Irlanda"},
	{"iso": "IL", "iso3": "ISR", "nome": "Israel", "nomeFormal": "Estado de Israel"},
	{"iso": "IT", "iso3": "ITA", "nome": "Italia", "nomeFormal": "República Italiana"},
	{"iso": "JM", "iso3": "JAM", "nome": "Jamaica", "nomeFormal": "Jamaica"},
	{"iso": "JP", "iso3": "JPN", "nome": "Japão", "nomeFormal": "Japão"},
	{"iso": "JO", "iso3": "JOR", "nome": "Jornânia", "nomeFormal": "Reino Hachemita da Jordânia"},
	{"iso": "KZ", "iso3": "KAZ", "nome": "Cazaquistão", "nomeFormal": "República do Cazaquistão"},
	{"iso": "KE", "iso3": "KEN", "nome": "Quênia", "nomeFormal": "República do Quênia"},
	{"iso": "KI", "iso3": "KIR", "nome": "Kiribati", "nomeFormal": "República do Kiribati"},
	{"iso": "KP", "iso3": "PRK", "nome": "Coreia do Norte", "nomeFormal": "República Democrática Popular da Coreia"},
	{"iso": "KR", "iso3": "KOR", "nome": "Coreia do Sul", "nomeFormal": "República da Coreia"},
	{"iso": "KW", "iso3": "KWT", "nome": "Kuwait", "nomeFormal": "Estado do Kuwait"},
	{"iso": "KG", "iso3": "KGZ", "nome": "Quirguistão", "nomeFormal": "República Quirguiz"},
	{"iso": "LA", "iso3": "LAO", "nome": "Laos", "nomeFormal": "República Democrática Popular Lau"},
	{"iso": "LV", "iso3": "LVA", "nome": "Letônia", "nomeFormal": "República da Letônia"},
	{"iso": "LB", "iso3": "LBN", "nome": "Líbano", "nomeFormal": "República Libanesa"},
	{"iso": "LS", "iso3": "LSO", "nome": "Lesoto", "nomeFormal": "Reino do Lesoto"},
	{"iso": "LR", "iso3": "LBR", "nome": "Libéria", "nomeFormal": "República da Libéria"},
	{"iso": "LY", "iso3": "LBY", "nome": "Líbia", "nomeFormal": "Líbia"},
	{"iso": "LI", "iso3": "LIE", "nome": "Liechtenstein", "nomeFormal": "Principado de Liechtenstein"},
	{"iso": "LT", "iso3": "LTU", "nome": "Lituânia", "nomeFormal": "República da Lituânia"},
	{"iso": "LU", "iso3": "LUX", "nome": "Luxemburgo", "nomeFormal": "Grão-Ducado do Luxemburgo"},
	{"iso": "MO", "iso3": "MAC", "nome": "Macao", "nomeFormal": "Macao"},
	{"iso": "MK", "iso3": "MKD", "nome": "Macedônia", "nomeFormal": "República da Macedônia"},
	{"iso": "MG", "iso3": "MDG", "nome": "Madagascar", "nomeFormal": "República de Madagascar"},
	{"iso": "MW", "iso3": "MWI", "nome": "Malawi", "nomeFormal": "República de Malawi"},
	{"iso": "MY", "iso3": "MYS", "nome": "Malásia", "nomeFormal": "Malásia"},
	{"iso": "MV", "iso3": "MDV", "nome": "Maldivas", "nomeFormal": "Reública de Maldivas"},
	{"iso": "ML", "iso3": "MLI", "nome": "Mali", "nomeFormal": "República do Mali"},
	{"iso": "MT", "iso3": "MLT", "nome": "Malta", "nomeFormal": "República de Malta"},
	{"iso": "MH", "iso3": "MHL", "nome": "Ilhas Marshall", "nomeFormal": "República das Ilhas Marshall"},
	{"iso": "MQ", "iso3": "MTQ", "nome": "Martinica", "nomeFormal": "Martinica"},
	{"iso": "MR", "iso3": "MRT", "nome": "Mauritânia", "nomeFormal": "República Islâmica da Mauritânia"},
	{"iso": "MU", "iso3": "MUS", "nome": "Maurício", "nomeFormal": "República de Maurício"},
	{"iso": "YT", "iso3": "MYT", "nome": "Mayotte", "nomeFormal": "Departamento de Mayotte"},
	{"iso": "MX", "iso3": "MEX", "nome": "México", "nomeFormal": "Estados Unidos Mexicanos"},
	{"iso": "FM", "iso3": "FSM", "nome": "Micronésia", "nomeFormal": "Estados Federados da Micronesia"},
	{"iso": "MD", "iso3": "MDA", "nome": "Moldova", "nomeFormal": "República de Moldova"},
	{"iso": "MC", "iso3": "MCO", "nome": "Mônaco", "nomeFormal": "Principado de Mônaco"},
	{"iso": "MN", "iso3": "MNG", "nome": "Mongólia", "nomeFormal": "Mongólia"},
	{"iso": "MS", "iso3": "MSR", "nome": "Montserrat", "nomeFormal": "Montserrat"},
	{"iso": "MA", "iso3": "MAR", "nome": "Marrocos", "nomeFormal": "Reino de Marrocos"},
	{"iso": "MZ", "iso3": "MOZ", "nome": "Moçambique", "nomeFormal": "República de Moçambique"},
	{"iso": "MM", "iso3": "MMR", "nome": "Birmânia", "nomeFormal": "República da União de Myanmar"},
	{"iso": "NA", "iso3": "NAM", "nome": "Namíbia", "nomeFormal": "República da Namíbia"},
	{"iso": "NR", "iso3": "NRU", "nome": "Nauru", "nomeFormal": "República de Nauru"},
	{"iso": "NP", "iso3": "NPL", "nome": "Nepal", "nomeFormal": "República Democrática Federativa do Nepal"},
	{"iso": "NL", "iso3": "NLD", "nome": "Holanda", "nomeFormal": "Holanda"},
	{"iso": "AN", "iso3": "ANT", "nome": "Antilhas Holandesas", "nomeFormal": "Antilhas Holandesas"},
	{"iso": "NC", "iso3": "NCL", "nome": "Nova Caledônia", "nomeFormal": "Nova Caledônia"},
	{"iso": "NZ", "iso3": "NZL", "nome": "Nova Zelândia", "nomeFormal": "Nova Zelândia"},
	{"iso": "NI", "iso3": "NIC", "nome": "Nicarágua", "nomeFormal": "República da Nicarágua"},
	{"iso": "NE", "iso3": "NER", "nome": "Niger", "nomeFormal": "República do Niger"},
	{"iso": "NG", "iso3": "NGA", "nome": "Nigéria", "nomeFormal": "República Federativa da Nigéria"},
	{"iso": "NU", "iso3": "NIU", "nome": "Niue", "nomeFormal": "Niue"},
	{"iso": "NF", "iso3": "NFK", "nome": "Ilha Norfolk", "nomeFormal": "Território da Ilha Norfolk"},
	{"iso": "MP", "iso3": "MNP", "nome": "Ilhas Marianas do Norte", "nomeFormal": "Comunidade das Ilhas Marianas do Norte"},
	{"iso": "NO", "iso3": "NOR", "nome": "Noruega", "nomeFormal": "Reino da Noruega"},
	{"iso": "OM", "iso3": "OMN", "nome": "Omã", "nomeFormal": "Sultanato de Omã"},
	{"iso": "PK", "iso3": "PAK", "nome": "Paquistão", "nomeFormal": "República Islâmica do Paquistão"},
	{"iso": "PW", "iso3": "PLW", "nome": "Palau", "nomeFormal": "República de Palau"},
	{"iso": "PS", "iso3": "PSE", "nome": "Palestina", "nomeFormal": "Estado da Palestina"},
	{"iso": "PA", "iso3": "PAN", "nome": "Panamá", "nomeFormal": "República do Panamá"},
	{"iso": "PG", "iso3": "PNG", "nome": "Papua-Nova Guiné", "nomeFormal": "Estado Independente da Papua-Nova Guiné"},
	{"iso": "PY", "iso3": "PRY", "nome": "Paraguai", "nomeFormal": "República do Paraguai"},
	{"iso": "PE", "iso3": "PER", "nome": "Peru", "nomeFormal": "República do Peru"},
	{"iso": "PH", "iso3": "PHL", "nome": "Filipinas", "nomeFormal": "República das Filipinas"},
	{"iso": "PN", "iso3": "PCN", "nome": "Ilhas Picárnia", "nomeFormal": "Ilhas Picárnia"},
	{"iso": "PL", "iso3": "POL", "nome": "Polônia", "nomeFormal": "República da Polônia"},
	{"iso": "PT", "iso3": "PRT", "nome": "Portugal", "nomeFormal": "República Portuguesa"},
	{"iso": "PR", "iso3": "PRI", "nome": "Porto Rico", "nomeFormal": "Comunidade do Porto Rico"},
	{"iso": "QA", "iso3": "QAT", "nome": "Catar", "nomeFormal": "Estado do Catar"},
	{"iso": "RE", "iso3": "REU", "nome": "Reunião", "nomeFormal": "Polônia"},
	{"iso": "RO", "iso3": "ROM", "nome": "Romênia", "nomeFormal": "Romênia"},
	{"iso": "RU", "iso3": "RUS", "nome": "Rússia", "nomeFormal": "Federação Russa"},
	{"iso": "RW", "iso3": "RWA", "nome": "Ruanda", "nomeFormal": "República da Ruanda"},
	{"iso": "SH", "iso3": "SHN", "nome": "Santa Helena", "nomeFormal": "Saint Helena"},
	{"iso": "KN", "iso3": "KNA", "nome": "São Cristóvão", "nomeFormal": "São Cristóvão"},
	{"iso": "LC", "iso3": "LCA", "nome": "Santa Lúcia", "nomeFormal": "Santa Lúcia"},
	{"iso": "PM", "iso3": "SPM", "nome": "São Pedro e Miquelon", "nomeFormal": "Coletividade Territorial de São Pedro e Miquelon"},
	{"iso": "VC", "iso3": "VCT", "nome": "São Vicente e Granadinas", "nomeFormal": "São Vicente e Granadinas"},
	{"iso": "WS", "iso3": "WSM", "nome": "Samoa", "nomeFormal": "Estado Independente de Samoa"},
	{"iso": "SM", "iso3": "SMR", "nome": "São Marino", "nomeFormal": "República de São Marino"},
	{"iso": "ST", "iso3": "STP", "nome": "Sao Tomé e Príncipe", "nomeFormal": "República Democrática de Sao Tomé e Príncipe"},
	{"iso": "SA", "iso3": "SAU", "nome": "Arábia Saudita", "nomeFormal": "Reino da Arábia Saudita"},
	{"iso": "SN", "iso3": "SEN", "nome": "Senegal", "nomeFormal": "República do Senegal"},
	{"iso": "CS", "iso3": "SRB", "nome": "Sérvia e Montenegro", "nomeFormal": "União Estatal de Sérvia e Montenegro"},
	{"iso": "SC", "iso3": "SYC", "nome": "Seicheles", "nomeFormal": "República das Seicheles"},
	{"iso": "SL", "iso3": "SLE", "nome": "República da Serra Leoa", "nomeFormal": "República da Serra Leoa"},
	{"iso": "SG", "iso3": "SGP", "nome": "Singapura", "nomeFormal": "República da Singapura"},
	{"iso": "SK", "iso3": "SVK", "nome": "Eslováquia", "nomeFormal": "República Eslovaca"},
	{"iso": "SI", "iso3": "SVN", "nome": "Eslovênia", "nomeFormal": "República da Eslovênia"},
	{"iso": "SB", "iso3": "SLB", "nome": "Ilhas Salomão", "nomeFormal": "Ilhas Salomão"},
	{"iso": "SO", "iso3": "SOM", "nome": "Somália", "nomeFormal": "República da Somália"},
	{"iso": "ZA", "iso3": "ZAF", "nome": "África do Sul", "nomeFormal": "República da África do Sul"},
	{"iso": "GS", "iso3": "SGS", "nome": "Ilhas Geórgia do Sul e Sandwich do Sul", "nomeFormal": "Ilhas Geórgia do Sul e Sandwich do Sul"},
	{"iso": "ES", "iso3": "ESP", "nome": "Espanha", "nomeFormal": "Reino da Espanha"},
	{"iso": "LK", "iso3": "LKA", "nome": "Sri Lanka", "nomeFormal": "República Democrática Socialista do Sri Lanka"},
	{"iso": "SD", "iso3": "SDN", "nome": "Sudão", "nomeFormal": "República do Sudão"},
	{"iso": "SR", "iso3": "SUR", "nome": "Suriname", "nomeFormal": "República do Suriname"},
	{"iso": "SJ", "iso3": "SJM", "nome": "Esvalbarde", "nomeFormal": "Esvalbarde"},
	{"iso": "SZ", "iso3": "SWZ", "nome": "Suazilândia", "nomeFormal": "Reino da Suazilândia"},
	{"iso": "SE", "iso3": "SWE", "nome": "Suécia", "nomeFormal": "Reino da Suécia"},
	{"iso": "CH", "iso3": "CHE", "nome": "Suiça", "nomeFormal": "Confederação Suiça"},
	{"iso": "SY", "iso3": "SYR", "nome": "Síria", "nomeFormal": "República Árabe Síria"},
	{"iso": "TW", "iso3": "TWN", "nome": "Taiwan", "nomeFormal": "Taiwan"},
	{"iso": "TJ", "iso3": "TJK", "nome": "Tajiquistão", "nomeFormal": "República do Tajiquistão"},
	{"iso": "TZ", "iso3": "TZA", "nome": "Tanzânia", "nomeFormal": "República Unida da Tanzânia"},
	{"iso": "TH", "iso3": "THA", "nome": "Tailândia", "nomeFormal": "Reino da Tailândia"},
	{"iso": "TL", "iso3": "TLS", "nome": "Timor-Leste", "nomeFormal": "República Democrática de Timor-Leste"},
	{"iso": "TG", "iso3": "TGO", "nome": "Togo", "nomeFormal": "República Togolesa"},
	{"iso": "TK", "iso3": "TKL", "nome": "Toquelau", "nomeFormal": "Toquelau"},
	{"iso": "TO", "iso3": "TON", "nome": "Tonga", "nomeFormal": "Reino de Tonga"},
	{"iso": "TT", "iso3": "TTO", "nome": "Trinidad e Tobago", "nomeFormal": "República da Trinidad e Tobago"},
	{"iso": "TN", "iso3": "TUN", "nome": "Tunísia", "nomeFormal": "República da Tunísia"},
	{"iso": "TR", "iso3": "TUR", "nome": "Turquia", "nomeFormal": "República da Turquia"},
	{"iso": "TM", "iso3": "TKM", "nome": "Turcomenistão", "nomeFormal": "Turcomenistão"},
	{"iso": "TC", "iso3": "TCA", "nome": "Ilhas Turks e Caicos", "nomeFormal": "Ilhas Turks e Caicos"},
	{"iso": "TV", "iso3": "TUV", "nome": "Tuvalu", "nomeFormal": "Tuvalu"},
	{"iso": "UG", "iso3": "UGA", "nome": "Uganda", "nomeFormal": "República de Uganda"},
	{"iso": "UA", "iso3": "UKR", "nome": "Ucrânia", "nomeFormal": "Ucrânia"},
	{"iso": "AE", "iso3": "ARE", "nome": "Emirados Árabes", "nomeFormal": "Emirados Árabes Unidos"},
	{"iso": "GB", "iso3": "GBR", "nome": "Reino Unido", "nomeFormal": "Reino Unido da Grã-Bretanha e Irlanda do Norte"},
	{"iso": "US", "iso3": "USA", "nome": "Estados Unidos", "nomeFormal": "Estados Unidos da América"},
	{"iso": "UM", "iso3": "UMI", "nome": "Ilhas Menores Distantes dos Estados Unidos", "nomeFormal": "Ilhas Menores Distantes dos Estados Unidos"},
	{"iso": "UY", "iso3": "URY", "nome": "Uruguai", "nomeFormal": "República Oriental do Uruguai"},
	{"iso": "UZ", "iso3": "UZB", "nome": "Uzbequistão", "nomeFormal": "República do Uzbequistão"},
	{"iso": "VU", "iso3": "VUT", "nome": "Vanuatu", "nomeFormal": "República de Vanuatu"},
	{"iso": "VE", "iso3": "VEN", "nome": "Venezuela", "nomeFormal": "República Bolivariana da Venezuela"},
	{"iso": "VN", "iso3": "VNM", "nome": "Vietnam", "nomeFormal": "República Socialista do Vietnam"},
	{"iso": "VG", "iso3": "VGB", "nome": "Ilhas Virgens Inglesas", "nomeFormal": "Ilhas Virgens"},
	{"iso": "VI", "iso3": "VIR", "nome": "Ilhas Virgens (USA)", "nomeFormal": "Ilhas Virgens dos Estados Unidos"},
	{"iso": "WF", "iso3": "WLF", "nome": "Wallis e Futuna", "nomeFormal": "Wallis e Futuna"},
	{"iso": "EH", "iso3": "ESH", "nome": "Saara Ocidental", "nomeFormal": "Saara Ocidental"},
	{"iso": "YE", "iso3": "YEM", "nome": "Iêmen", "nomeFormal": "República do Iêmen"},
	{"iso": "ZM", "iso3": "ZMB", "nome": "Zâmbia", "nomeFormal": "República do Zâmbia"},
	{"iso": "ZW", "iso3": "ZWE", "nome": "Zimbábue", "nomeFormal": "República do Zimbábue"}
]

export default countries